# Why Numpy?

Python이 C, java와 같이 general purpose를 가진 언어. R과 달리 통계, 데이터 분석을 위해 태어난 언어가 아님. 그런데 Python이 쉬워서 다양한 도메인, 과학적 계산에 사용하는 사람들이 많았음 ex)물리학자 등..
필요에 의해 sklearn, Numpy (= Numeric Python), Scipy, Pandas, matplotlib 등 탄생!

In [2]:
import numpy as np

In [9]:
a = np.array([1,2,3], float)
print(type(a))

<class 'numpy.ndarray'>


In [12]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [3]:
a = np.array([1,4,0], float)
b = np.array([2,2,1], float)

In [5]:
np.inner(a,b)

10.0

In [6]:
np.outer(a,b)

array([[ 2.,  2.,  1.],
       [ 8.,  8.,  4.],
       [ 0.,  0.,  0.]])

In [7]:
np.cross(a,b)

array([ 4., -1., -6.])

In [12]:
first_array = np.array([[1,2,3], [4,5,6]])
print(first_array)
print(type(first_array))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [11]:
first_arange = np.arange(1, 15, 2) # it is also array!
print(first_arange)
print(type(first_arange))

[ 1  3  5  7  9 11 13]
<class 'numpy.ndarray'>


In [17]:
zeros, ones = np.zeros((3,3)), np.ones((3,3))
print(zeros)
print(ones)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [57]:
np.random.seed(0)
rand = np.random.rand(3,3)
rand

array([[ 0.5488135 ,  0.71518937,  0.60276338],
       [ 0.54488318,  0.4236548 ,  0.64589411],
       [ 0.43758721,  0.891773  ,  0.96366276]])

In [58]:
np.random.seed(0)
random = np.random.random((3,3))
random

array([[ 0.5488135 ,  0.71518937,  0.60276338],
       [ 0.54488318,  0.4236548 ,  0.64589411],
       [ 0.43758721,  0.891773  ,  0.96366276]])

In [70]:
a = np.array([3,2,10], float)
a # numpy.ndarray object

array([  3.,   2.,  10.])

In [71]:
a.sum()

15.0

In [72]:
a.prod()

60.0

In [75]:
x = np.array([[1,2], [3,4]])
print(x.sum(axis = 0))
print("*"*20)
print(x.sum(axis = 1))

[4 6]
********************
[3 7]


In [80]:
points = [[9,2,8], [4,7,2], [3,4,4], [5,6,9], [5,0,7], [8,2,7], [0,3,2], [7,3,0], [6,1,1], [2,9,6]]
qPoint = [4,5,3]
minidx = -1
mindist = -1

for idx, point in enumerate(points):
    dist = sum([(dp - dq)**2 for dp, dq in zip(point, qPoint)])**0.5
    if dist < mindist or mindist < 0:
        mindist = dist
        minidx = idx

print("Nearest point to q :", points[minidx])

Nearest point to q : [3, 4, 4]
